<a href="https://colab.research.google.com/github/emran-bigdeli/Modified-HRP/blob/main/CBOE_%26_CME.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install wrds

Collecting wrds
  Downloading wrds-3.1.6-py3-none-any.whl (12 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from wrds) (1.22.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from wrds) (1.5.3)
Collecting psycopg2-binary (from wrds)
  Downloading psycopg2_binary-2.9.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 19.1 MB/s eta 0:00:00
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from wrds) (1.10.1)
Collecting sqlalchemy<2 (from wrds)
  Downloading SQLAlchemy-1.4.49-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 21.0 MB/s eta 0:00:00
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy<2->wrds) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas->wrds) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->wrds) (2022.7.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas->wrds) (1.16.0)
Installing collected packages: sqlalchemy, psycopg2-binary, wrds
  Attempting uninstall: sqlalchemy
    Found existing installation: SQLAlchemy 2.0.18
    Uninstalling SQLAlchemy-2.0.18:
      Successfully uninstalled SQLAlchemy-2.0.18
Successfully installed psycopg2-binary-2.9.6 sqlalchemy-1.4.49 wrds-3.1.6

In [3]:
import wrds
import pandas as pd
from google.colab import data_table

conn = wrds.Connection(wrds_username='emran_bigdeli')

Enter your WRDS username [emran_bigdeli]:emran_bigdeli
Enter your password:··········
WRDS recommends setting up a .pgpass file.
Create .pgpass file now [y/n]?: y
Created .pgpass file successfully.
You can create this file yourself at any time with the create_pgpass_file() function.
Loading library list...
Done

In [ ]:
conn.list_tables(library='optionm')

['country',
 'currency',
 'distrd',
 'distribution',
 'distribution_projection',
 'distrprojd1996',
 'distrprojd1997',
 'distrprojd1998',
 'distrprojd1999',
 'distrprojd2000',
 'distrprojd2001',
 'distrprojd2002',
 'distrprojd2003',
 'distrprojd2004',
 'distrprojd2005',
 'distrprojd2006',
 'distrprojd2007',
 'distrprojd2008',
 'distrprojd2009',
 'distrprojd2010',
 'distrprojd2011',
 'distrprojd2012',
 'distrprojd2013',
 'distrprojd2014',
 'distrprojd2015',
 'distrprojd2016',
 'distrprojd2017',
 'distrprojd2018',
 'distrprojd2019',
 'distrprojd2020',
 'distrprojd2021',
 'distrprojd2022',
 'distrprojd2023',
 'exchange',
 'exchgd',
 'forward_price',
 'futures',
 'futures_price',
 'fwdprd1996',
 'fwdprd1997',
 'fwdprd1998',
 'fwdprd1999',
 'fwdprd2000',
 'fwdprd2001',
 'fwdprd2002',
 'fwdprd2003',
 'fwdprd2004',
 'fwdprd2005',
 'fwdprd2006',
 'fwdprd2007',
 'fwdprd2008',
 'fwdprd2009',
 'fwdprd2010',
 'fwdprd2011',
 'fwdprd2012',
 'fwdprd2013',
 'fwdprd2014',
 'fwdprd2015',
 'fwdprd2016',
 'fwdprd2017',
 'fwdprd2018',
 'fwdprd2019',
 'fwdprd2020',
 'fwdprd2021',
 'fwdprd2022',
 'fwdprd2023',
 'historical_volatility',
 'hvold1996',
 'hvold1997',
 'hvold1998',
 'hvold1999',
 'hvold2000',
 'hvold2001',
 'hvold2002',
 'hvold2003',
 'hvold2004',
 'hvold2005',
 'hvold2006',
 'hvold2007',
 'hvold2008',
 'hvold2009',
 'hvold2010',
 'hvold2011',
 'hvold2012',
 'hvold2013',
 'hvold2014',
 'hvold2015',
 'hvold2016',
 'hvold2017',
 'hvold2018',
 'hvold2019',
 'hvold2020',
 'hvold2021',
 'hvold2022',
 'hvold2023',
 'idxdvd',
 'index_dividend',
 'indexd',
 'op_view',
 'op_view_tick',
 'opinfd',
 'opprcd1996',
 'opprcd1997',
 'opprcd1998',
 'opprcd1999',
 'opprcd2000',
 'opprcd2001',
 'opprcd2002',
 'opprcd2003',
 'opprcd2004',
 'opprcd2005',
 'opprcd2006',
 'opprcd2007',
 'opprcd2008',
 'opprcd2009',
 'opprcd2010',
 'opprcd2011',
 'opprcd2012',
 'opprcd2013',
 'opprcd2014',
 'opprcd2015',
 'opprcd2016',
 'opprcd2017',
 'opprcd2018',
 'opprcd2019',
 'opprcd2020',
 'opprcd2021',
 'opprcd2022',
 'opprcd2023',
 'option',
 'option_history',
 'option_price_2002',
 'option_price_2003',
 'option_price_2004',
 'option_price_2005',
 'option_price_2006',
 'option_price_2007',
 'option_price_2008',
 'option_price_2009',
 'option_price_2010',
 'option_price_2011',
 'option_price_2012',
 'option_price_2013',
 'option_price_2014',
 'option_price_2015',
 'option_price_2016',
 'option_price_2017',
 'option_price_2018',
 'option_price_2019',
 'option_price_2020',
 'option_price_2021',
 'option_price_2022',
 'option_price_2023',
 'option_price_view',
 'optionmeurnames',
 'optionmnames',
 'opvold',
 'release',
 'rollover',
 'secnmd',
 'secprd',
 'secprd1996',
 'secprd1997',
 'secprd1998',
 'secprd1999',
 'secprd2000',
 'secprd2001',
 'secprd2002',
 'secprd2003',
 'secprd2004',
 'secprd2005',
 'secprd2006',
 'secprd2007',
 'secprd2008',
 'secprd2009',
 'secprd2010',
 'secprd2011',
 'secprd2012',
 'secprd2013',
 'secprd2014',
 'secprd2015',
 'secprd2016',
 'secprd2017',
 'secprd2018',
 'secprd2019',
 'secprd2020',
 'secprd2021',
 'secprd2022',
 'secprd2023',
 'securd',
 'securd1',
 'security',
 'security_name',
 'security_price',
 'std_option_price_2002',
 'std_option_price_2003',
 'std_option_price_2004',
 'std_option_price_2005',
 'std_option_price_2006',
 'std_option_price_2007',
 'std_option_price_2008',
 'std_option_price_2009',
 'std_option_price_2010',
 'std_option_price_2011',
 'std_option_price_2012',
 'std_option_price_2013',
 'std_option_price_2014',
 'std_option_price_2015',
 'std_option_price_2016',
 'std_option_price_2017',
 'std_option_price_2018',
 'std_option_price_2019',
 'std_option_price_2020',
 'std_option_price_2021',
 'std_option_price_2022',
 'std_option_price_2023',
 'std_option_price_view',
 'stdopd1996',
 'stdopd1997',
 'stdopd1998',
 'stdopd1999',
 'stdopd2000',
 'stdopd2001',
 'stdopd2002',
 'stdopd2003',
 'stdopd2004',
 'stdopd2005',
 'stdopd2006',
 'stdopd2007',
 'stdopd2008',
 'stdopd2009',
 'stdopd2010',
 'stdopd2011',
 'stdopd2012',
 'stdopd2013',
 'stdopd2014',
 'stdopd2015',
 'stdopd2016',
 'stdopd2017',
 'stdopd2018',
 'stdopd2019',
 'stdopd2020',
 'stdopd2021',
 'stdopd2022',
 'stdopd2023',
 'tick_option_price_2006',
 'tick_option_price_2007',
 'tick_option_price_2008',
 'tick_option_price_2009',
 'tick_option_price_2010',
 'tick_option_price_2011',
 'tick_option_price_2012',
 'tick_option_price_2013',
 'tick_option_price_2014',
 'tick_option_price_2015',
 'tick_option_price_2016',
 'tick_option_price_2017',
 'tick_option_price_2018',
 'tick_option_price_2019',
 'tick_option_price_2020',
 'tick_option_price_2021',
 'tick_option_price_2022',
 'tick_option_price_2023',
 'tick_option_price_view',
 'tick_std_option_price_2006',
 'tick_std_option_price_2007',
 'tick_std_option_price_2008',
 'tick_std_option_price_2009',
 'tick_std_option_price_2010',
 'tick_std_option_price_2011',
 'tick_std_option_price_2012',
 'tick_std_option_price_2013',
 'tick_std_option_price_2014',
 'tick_std_option_price_2015',
 'tick_std_option_price_2016',
 'tick_std_option_price_2017',
 'tick_std_option_price_2018',
 'tick_std_option_price_2019',
 'tick_std_option_price_2020',
 'tick_std_option_price_2021',
 'tick_std_option_price_2022',
 'tick_std_option_price_2023',
 'tick_std_option_price_view',
 'tick_volatility_surface_2006',
 'tick_volatility_surface_2007',
 'tick_volatility_surface_2008',
 'tick_volatility_surface_2009',
 'tick_volatility_surface_2010',
 'tick_volatility_surface_2011',
 'tick_volatility_surface_2012',
 'tick_volatility_surface_2013',
 'tick_volatility_surface_2014',
 'tick_volatility_surface_2015',
 'tick_volatility_surface_2016',
 'tick_volatility_surface_2017',
 'tick_volatility_surface_2018',
 'tick_volatility_surface_2019',
 'tick_volatility_surface_2020',
 'tick_volatility_surface_2021',
 'tick_volatility_surface_2022',
 'tick_volatility_surface_2023',
 'tick_volatility_surface_view',
 'ticker',
 'volatility_surface_2002',
 'volatility_surface_2003',
 'volatility_surface_2004',
 'volatility_surface_2005',
 'volatility_surface_2006',
 'volatility_surface_2007',
 'volatility_surface_2008',
 'volatility_surface_2009',
 'volatility_surface_2010',
 'volatility_surface_2011',
 'volatility_surface_2012',
 'volatility_surface_2013',
 'volatility_surface_2014',
 'volatility_surface_2015',
 'volatility_surface_2016',
 'volatility_surface_2017',
 'volatility_surface_2018',
 'volatility_surface_2019',
 'volatility_surface_2020',
 'volatility_surface_2021',
 'volatility_surface_2022',
 'volatility_surface_2023',
 'volatility_surface_view',
 'vsurfd1996',
 'vsurfd1997',
 'vsurfd1998',
 'vsurfd1999',
 'vsurfd2000',
 'vsurfd2001',
 'vsurfd2002',
 'vsurfd2003',
 'vsurfd2004',
 'vsurfd2005',
 'vsurfd2006',
 'vsurfd2007',
 'vsurfd2008',
 'vsurfd2009',
 'vsurfd2010',
 'vsurfd2011',
 'vsurfd2012',
 'vsurfd2013',
 'vsurfd2014',
 'vsurfd2015',
 'vsurfd2016',
 'vsurfd2017',
 'vsurfd2018',
 'vsurfd2019',
 'vsurfd2020',
 'vsurfd2021',
 'vsurfd2022',
 'vsurfd2023',
 'zero_curve',
 'zerocd']

In [ ]:
conn.get_table(library='optionm', table='exchgd', obs=1000)

      secid effect_date  seq_num status exchange add_del exch_flag
0    5001.0  1996-01-01      1.0      $        F       *         4
1    5001.0  2007-03-08      1.0      D        F    None         0
2    5002.0  1996-01-01      1.0      $        F       *         4
3    5002.0  1996-02-01      1.0      X        F    None         0
4    5003.0  1996-01-01      1.0      $        O       *        16
..      ...         ...      ...    ...      ...     ...       ...
995  5467.0  1996-01-01      1.0      $        X    None         0
996  5468.0  1996-01-01      1.0      $        A       *         1
997  5468.0  2000-01-10      1.0      X        A    None         0
998  5469.0  1996-01-01      1.0      $        O       *        16
999  5470.0  1996-01-01      1.0      $        F       *         4

[1000 rows x 7 columns]

In [6]:
conn.get_table(library='optionm', table='opprcd2022', obs=10000)

,secid,date,symbol,symbol_flag,exdate,last_date,cp_flag,strike_price,best_bid,best_offer,...,theta,optionid,cfadj,am_settlement,contract_size,ss_flag,forward_price,expiry_indicator,root,suffix
0,101273.0,2022-02-11,ALL 220218C160000,1,2022-02-18,None,C,160000.0,0.0,0.75,...,-50.826810,144136075.0,1.0,0.0,100.0,0,None,None,None,None
1,101273.0,2022-02-11,ALL 220218C165000,1,2022-02-18,None,C,165000.0,0.0,0.25,...,-22.247990,144136076.0,1.0,0.0,100.0,0,None,None,None,None
2,101273.0,2022-02-11,ALL 220218C65000,1,2022-02-18,None,C,65000.0,56.6,60.30,...,-14.088260,144136077.0,1.0,0.0,100.0,0,None,None,None,None
3,101273.0,2022-02-11,ALL 220218C70000,1,2022-02-18,None,C,70000.0,51.6,55.30,...,-13.832770,144136078.0,1.0,0.0,100.0,0,None,None,None,None
4,101273.0,2022-02-11,ALL 220218C75000,1,2022-02-18,None,C,75000.0,46.6,50.30,...,-13.555830,144136079.0,1.0,0.0,100.0,0,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,101273.0,2022-03-18,ALL 221021C100000,1,2022-10-21,None,C,100000.0,33.0,36.40,...,-5.605469,145320389.0,1.0,0.0,100.0,0,None,None,None,None
9996,101273.0,2022-03-18,ALL 221021C105000,1,2022-10-21,None,C,105000.0,29.6,30.70,...,-6.422541,145320390.0,1.0,0.0,100.0,0,None,None,None,None
9997,101273.0,2022-03-18,ALL 221021C110000,1,2022-10-21,None,C,110000.0,24.8,27.30,...,-7.711731,145320391.0,1.0,0.0,100.0,0,None,None,None,None
9998,101273.0,2022-03-18,ALL 221021C115000,1,2022-10-21,None,C,115000.0,21.1,23.00,...,-8.523783,145320392.0,1.0,0.0,100.0,0,None,None,None,None
9999,101273.0,2022-03-18,ALL 221021C120000,1,2022-10-21,2022-03-09,C,120000.0,17.3,18.90,...,-8.918029,145320393.0,1.0,0.0,100.0,0,None,None,None,None

Warning: Total number of columns (26) exceeds max_columns (20) limiting to first (20) columns.

In [8]:
options_data = conn.raw_sql("""SELECT symbol, strike_price, best_bid, best_offer, date,  exdate  FROM optionm.opprcd2022 WHERE

                            (secid=108105 or secid=109820) and
                            cp_flag='C' and
                            date >= '2022-06-22'""")

# Removing the SPXW from the data, because their expiration have different format but same date!
options_data = options_data[~(options_data["symbol"].str[3] == 'W')]

#keeping the first three character which SPX or SPY
options_data['symbol'] = options_data["symbol"].str[:3]

#Keeping Strike prices that is common for both SPX and SPY. SPY step is 10 and SPX step is 25 in strike prices.
options_data = options_data[(options_data["strike_price"]%50==0)]

#Adjusting the price. SPY price is tenth of SPX
options_data.loc[options_data['symbol'] == 'SPY', 'strike_price'] /= 100
options_data.loc[options_data['symbol'] == 'SPX', 'strike_price'] /= 1000
options_data.loc[options_data['symbol'] == 'SPY', 'best_bid'] *= 10
options_data.loc[options_data['symbol'] == 'SPY', 'best_offer'] *= 10
options_data['exdate'] = options_data['exdate'].astype(str)
options_data['midpoint']= (options_data['best_bid']+options_data['best_offer'])/2
options_data['rel_spread']= (options_data['best_offer']-options_data['best_bid'])/options_data['midpoint']

#Keeping Strike prices that is common for both SPX and SPY. SPY step is 10 and SPX step is 25 in strike prices.
options_data = options_data[(options_data["strike_price"]%50==0)]

SPX=4400

options_data.loc[options_data['strike_price']>SPX,'moneyness'] = "OTC"
options_data.loc[options_data['strike_price']<SPX,'moneyness'] = "ITC"
options_data.loc[options_data['strike_price']==SPX,'moneyness'] = "ATC"

<ipython-input-8-7fe15efce5fd>:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  options_data.loc[options_data['strike_price']>SPX,'moneyness'] = "OTC"

In [ ]:
options_data = conn.raw_sql("""SELECT secid, exchange, exch_flag  FROM optionm.exchgd WHERE

                            secid=109820""")

In [9]:
options_data

,symbol,strike_price,best_bid,best_offer,date,exdate,midpoint,rel_spread,moneyness
0,SPX,1000.0,2757.8,2764.5,2022-06-22,2022-07-15,2761.15,0.002427,ITC
1,SPX,1100.0,2657.9,2666.0,2022-06-22,2022-07-15,2661.95,0.003043,ITC
2,SPX,1200.0,2558.0,2566.1,2022-06-22,2022-07-15,2562.05,0.003162,ITC
3,SPX,1300.0,2457.2,2465.8,2022-06-22,2022-07-15,2461.50,0.003494,ITC
4,SPX,1400.0,2358.3,2366.3,2022-06-22,2022-07-15,2362.30,0.003387,ITC
...,...,...,...,...,...,...,...,...,...
386485,SPY,4600.0,0.1,0.2,2022-06-22,2022-07-05,0.15,0.666667,OTC
386486,SPY,4650.0,0.1,0.2,2022-06-22,2022-07-05,0.15,0.666667,OTC
386487,SPY,4700.0,0.0,0.1,2022-06-22,2022-07-05,0.05,2.000000,OTC
386488,SPY,4800.0,0.0,0.1,2022-06-22,2022-07-05,0.05,2.000000,OTC
386489,SPY,4900.0,0.0,0.1,2022-06-22,2022-07-05,0.05,2.000000,OTC

In [12]:
options_data[(options_data['strike_price'] >= 4200) & (options_data['strike_price'] <= 4900) & (options_data['exdate'] == "2024-12-20")].sort_values(['strike_price'])

,symbol,strike_price,best_bid,best_offer,date,exdate,midpoint,rel_spread,moneyness
2829,SPX,4200.0,379.1,397.8,2022-06-22,2024-12-20,388.45,0.048140,ITC
144424,SPX,4200.0,481.0,487.0,2022-12-07,2024-12-20,484.00,0.012397,ITC
125540,SPX,4200.0,521.0,531.9,2022-12-05,2024-12-20,526.45,0.020705,ITC
122551,SPX,4200.0,564.8,576.7,2022-12-02,2024-12-20,570.75,0.020850,ITC
117326,SPX,4200.0,570.0,581.6,2022-12-01,2024-12-20,575.80,0.020146,ITC
...,...,...,...,...,...,...,...,...,...
486091,SPY,4900.0,300.0,337.1,2022-08-10,2024-12-20,318.55,0.116465,OTC
479069,SPY,4900.0,341.8,386.8,2022-08-15,2024-12-20,364.30,0.123525,OTC
474580,SPY,4900.0,335.0,385.0,2022-08-12,2024-12-20,360.00,0.138889,OTC
107751,SPX,4900.0,186.0,195.8,2022-07-08,2024-12-20,190.90,0.051336,OTC
386308,SPY,4900.0,125.0,175.0,2022-12-30,2024-12-20,150.00,0.333333,OTC

In [10]:
subsample=options_data[(options_data['strike_price'] >= 4300) & (options_data['strike_price'] <= 4600) & (options_data['exdate'].str[:4] == "2023")].sort_values(['strike_price'])
table = subsample.pivot(index=["moneyness", 'strike_price', "symbol"], columns='exdate', values='rel_spread').dropna(axis=1)
table

ValueError: ignored

In [11]:
options_data[(options_data['strike_price'] >= 4300) & (options_data['strike_price'] <= 4600) & (options_data['exdate'] == "2023-06-16")].groupby(['moneyness','strike_price',"exdate",'symbol']).mean()

<ipython-input-11-f3ff86c358fb>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  options_data[(options_data['strike_price'] >= 4300) & (options_data['strike_price'] <= 4600) & (options_data['exdate'] == "2023-06-16")].groupby(['moneyness','strike_price',"exdate",'symbol']).mean()

                                            best_bid  best_offer    midpoint  \
moneyness strike_price exdate     symbol
ATC       4400.0       2023-06-16 SPX     129.908209  131.415672  130.661940
                                  SPY     125.842537  130.329851  128.086194
ITC       4300.0       2023-06-16 SPX     165.114925  166.716418  165.915672
                                  SPY     160.550746  165.838806  163.194776
          4350.0       2023-06-16 SPX     146.783582  148.347761  147.565672
                                  SPY     142.585075  147.244030  144.914552
OTC       4450.0       2023-06-16 SPX     114.441045  115.900746  115.170896
                                  SPY     110.581343  114.917910  112.749627
          4500.0       2023-06-16 SPX     100.380597  101.779851  101.080224
                                  SPY      97.058955  100.889552   98.974254
          4550.0       2023-06-16 SPX      87.632836   88.979104   88.305970
                                  SPY      84.382090   88.273881   86.327985
          4600.0       2023-06-16 SPX      76.217910   77.497761   76.857836
                                  SPY      73.182836   77.102239   75.142537

                                          rel_spread
moneyness strike_price exdate     symbol
ATC       4400.0       2023-06-16 SPX       0.012900
                                  SPY       0.038979
ITC       4300.0       2023-06-16 SPX       0.010553
                                  SPY       0.034013
          4350.0       2023-06-16 SPX       0.011707
                                  SPY       0.035407
OTC       4450.0       2023-06-16 SPX       0.014329
                                  SPY       0.044371
          4500.0       2023-06-16 SPX       0.015919
                                  SPY       0.045443
          4550.0       2023-06-16 SPX       0.017764
                                  SPY       0.053350
          4600.0       2023-06-16 SPX       0.019624
                                  SPY       0.062112

In [ ]:
df_filtered = options_data[options_data['exdate'].isin(options_data['exdate'].value_counts()[options_data['exdate'].value_counts() > 1].index)]

In [ ]:
options_data

,symbol,strike_price,best_bid,best_offer,date,exdate,midpoint,rel_spread,moneyness
0,SPX,1000.0,2757.8,2764.5,2022-06-22,2022-07-15,2761.15,0.002427,ITC
1,SPX,1100.0,2657.9,2666.0,2022-06-22,2022-07-15,2661.95,0.003043,ITC
2,SPX,1200.0,2558.0,2566.1,2022-06-22,2022-07-15,2562.05,0.003162,ITC
3,SPX,1300.0,2457.2,2465.8,2022-06-22,2022-07-15,2461.50,0.003494,ITC
4,SPX,1400.0,2358.3,2366.3,2022-06-22,2022-07-15,2362.30,0.003387,ITC
...,...,...,...,...,...,...,...,...,...
386475,SPY,6400.0,20.0,70.0,2022-12-30,2025-12-19,45.00,1.111111,OTC
386476,SPY,6450.0,15.0,65.0,2022-12-30,2025-12-19,40.00,1.250000,OTC
386477,SPY,6500.0,26.0,65.0,2022-12-30,2025-12-19,45.50,0.857143,OTC
386480,SPY,4150.0,0.5,0.6,2022-06-22,2022-07-01,0.55,0.181818,ITC
386485,SPY,4200.0,0.3,0.4,2022-06-22,2022-07-01,0.35,0.285714,ITC

In [ ]:
df_filtered = df[df['A'].isin(df['A'].value_counts()[df['A'].value_counts() > 1].index)]